/*
 * This file is generated by jOOQ.
 */
package gorbats.dockerproject.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAccount implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String name;

    public UserAccount() {}

    public UserAccount(UserAccount value) {
        this.id = value.id;
        this.name = value.name;
    }

    public UserAccount(
        Long   id,
        String name
    ) {
        this.id = id;
        this.name = name;
    }

    /**
     * Getter for <code>public.user_account.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.user_account.id</code>.
     */
    public UserAccount setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.user_account.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.user_account.name</code>.
     */
    public UserAccount setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserAccount other = (UserAccount) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserAccount (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
